const data = [
  {
    id: "1",
    type: "startNode",
    position: { x: 220, y: -20 },
    data: { label: "告警" },
  },
  {
    id: "2",
    type: "squareNode",
    position: { x: 260, y: 60 },
    data: { label: "查看GC线程CPU" },
  },
  {
    id: "3",
    type: "diamondNode",
    position: { x: 100, y: 160 },
    data: { label: ">60%" },
  },
  {
    id: "4",
    type: "diamondNode",
    position: { x: 330, y: 160 },
    data: { label: "<=60%" },
  },
  {
    id: "5",
    type: "endNode",
    position: { x: 80, y: 300 },
    data: { label: "未知" },
  },
  {
    id: "6",
    type: "squareNode",
    position: { x: 430, y: 280 },
    data: { label: "查看业务线程CPU" },
  },
  {
    id: "7",
    type: "endNode",
    position: { x: 290, y: 370 },
    data: { label: "END" },
  },
  {
    id: "e5",
    source: "4",
    target: "6",
    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { strokeWidth: 2 },
  },
  {
    source: "3",
    sourceHandle: null,
    target: "5",
    targetHandle: null,
    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { strokeWidth: 2 },
    id: "reactflow__edge-3null-5null",
  },
  {
    source: "2",
    sourceHandle: null,
    target: "3",
    targetHandle: null,
    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { strokeWidth: 2 },
    id: "reactflow__edge-2null-3null",
  },
  {
    source: "2",
    sourceHandle: null,
    target: "4",
    targetHandle: null,
    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { strokeWidth: 2 },
    id: "reactflow__edge-2null-4null",
  },
  {
    source: "1",
    sourceHandle: null,
    target: "2",
    targetHandle: null,
    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { strokeWidth: 2 },
    id: "reactflow__edge-1null-2null",
  },
  {
    source: "6",
    sourceHandle: null,
    target: "7",
    targetHandle: null,
    type: "smoothstep",
    arrowHeadType: "arrowclosed",
    style: { strokeWidth: 2 },
    id: "reactflow__edge-6null-7null",
  },
  {
    source: "1",
    sourceHandle: null,
    target: "7",
    targetHandle: null,
    type: "smoothstep",
    animated: true,
    arrowHeadType: "arrowclosed",
    style: { strokeWidth: 2 },
    id: "reactflow__edge-1null-7null",
  },
  {
    source: "1",
    sourceHandle: null,
    target: "3",
    targetHandle: null,
    type: "smoothstep",
    label: "告警测试",
    labelStyle: { fill: "#000", fillColor: "#e6e6e6" },
    // labelBgStyle: { "backgroundColor": "red" },
    // labelShowBg: false,
    arrowHeadType: "arrowclosed",
    style: { strokeWidth: 2 },
    id: "reactflow__edge-1null-3null",
  },
];

export default data;
